// <auto-generated />
using Armory.Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Armory.Store.Migrations
{
    [DbContext(typeof(ArmoryContext))]
    partial class ArmoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Armory.Store.AchievementRow", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("Points")
                        .HasColumnType("INTEGER")
                        .HasColumnName("points");

                    b.Property<long>("Unrepeatable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unrepeatable");

                    b.HasKey("Id");

                    b.ToTable("achievement", (string)null);
                });

            modelBuilder.Entity("Armory.Store.AttributionRow", b =>
                {
                    b.Property<long>("AchievementId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("achievement_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RealmSlug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.HasKey("AchievementId");

                    b.ToTable("attribution", (string)null);
                });

            modelBuilder.Entity("Armory.Store.ChangeRow", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("At")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("at");

                    b.Property<long>("Gone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("gone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("machine");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.HasKey("Seq");

                    b.HasIndex("Machine", "Seq")
                        .HasDatabaseName("change_machine");

                    b.HasIndex("Scope", "Key")
                        .IsUnique()
                        .HasDatabaseName("change_scope_key");

                    b.ToTable("change", (string)null);
                });

            modelBuilder.Entity("Armory.Store.CharacterRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("class");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("faction");

                    b.Property<long>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("race");

                    b.Property<long>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realm_id");

                    b.Property<string>("RealmName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_name");

                    b.Property<long>("WowAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wow_account_id");

                    b.HasKey("RealmSlug", "Name");

                    b.ToTable("character", (string)null);
                });

            modelBuilder.Entity("Armory.Store.CollectibleRow", b =>
                {
                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("json");

                    b.Property<long>("Owned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("owned");

                    b.HasKey("Kind", "Id");

                    b.ToTable("collectible", (string)null);
                });

            modelBuilder.Entity("Armory.Store.CriterionRow", b =>
                {
                    b.Property<long>("CriterionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("criterion_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.HasKey("CriterionId");

                    b.ToTable("criterion", (string)null);
                });

            modelBuilder.Entity("Armory.Store.CurrencyRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("currency_id");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount");

                    b.HasKey("RealmSlug", "Name", "CurrencyId");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("Armory.Store.DetailRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("FetchedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("json");

                    b.HasKey("RealmSlug", "Name");

                    b.ToTable("detail", (string)null);
                });

            modelBuilder.Entity("Armory.Store.EarnedCurrencyRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("currency_id");

                    b.Property<long>("AccountWide")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_wide");

                    b.Property<long>("Earned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("earned");

                    b.Property<long>("Gained")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gained");

                    b.Property<long>("TracksEarned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tracks_earned");

                    b.Property<long>("Transferable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transferable");

                    b.HasKey("RealmSlug", "Name", "CurrencyId");

                    b.ToTable("earned_currency", (string)null);
                });

            modelBuilder.Entity("Armory.Store.EarnedReputationRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("FactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("faction_id");

                    b.Property<long>("AccountWide")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_wide");

                    b.Property<long>("Points")
                        .HasColumnType("INTEGER")
                        .HasColumnName("points");

                    b.Property<long>("Renown")
                        .HasColumnType("INTEGER")
                        .HasColumnName("renown");

                    b.Property<long>("RenownSeen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("renown_seen");

                    b.HasKey("RealmSlug", "Name", "FactionId");

                    b.ToTable("earned_reputation", (string)null);
                });

            modelBuilder.Entity("Armory.Store.EncounterRow", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Loot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("loot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("encounter", (string)null);
                });

            modelBuilder.Entity("Armory.Store.EnrolmentRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("RealmSlug", "Name");

                    b.ToTable("enrolment", (string)null);
                });

            modelBuilder.Entity("Armory.Store.EntryRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("WrittenAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("written_at");

                    b.HasKey("RealmSlug", "Name", "StartedAt");

                    b.ToTable("entry", (string)null);
                });

            modelBuilder.Entity("Armory.Store.ForgottenRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("At")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("at");

                    b.HasKey("RealmSlug", "Name", "StartedAt");

                    b.ToTable("forgotten", (string)null);
                });

            modelBuilder.Entity("Armory.Store.GoalRow", b =>
                {
                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.Property<long>("AchievementId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("achievement_id");

                    b.Property<string>("Attestation")
                        .HasColumnType("TEXT")
                        .HasColumnName("attestation");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bucket");

                    b.Property<string>("Standing")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("standing");

                    b.HasKey("RunId", "AchievementId");

                    b.ToTable("goal", (string)null);
                });

            modelBuilder.Entity("Armory.Store.InstanceRow", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Encounters")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("encounters");

                    b.Property<string>("Expansion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("expansion");

                    b.Property<long?>("Map")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("instance", (string)null);
                });

            modelBuilder.Entity("Armory.Store.ItemRow", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("quality");

                    b.Property<long>("Sellable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("sellable");

                    b.HasKey("ItemId");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("Armory.Store.PetHeldRow", b =>
                {
                    b.Property<long>("SpeciesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("species_id");

                    b.Property<long>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count");

                    b.HasKey("SpeciesId");

                    b.ToTable("pet_held", (string)null);
                });

            modelBuilder.Entity("Armory.Store.PriceRow", b =>
                {
                    b.Property<long>("Realm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realm");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("Variant")
                        .HasColumnType("TEXT")
                        .HasColumnName("variant");

                    b.Property<string>("SeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("seen_at");

                    b.Property<long>("Listings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("listings");

                    b.Property<long>("Median")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("median");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<long>("Tenth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("tenth");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_price");

                    b.HasKey("Realm", "ItemId", "Variant", "SeenAt");

                    b.HasIndex("SeenAt")
                        .HasDatabaseName("price_seen_at");

                    b.HasIndex("ItemId", "Realm", "SeenAt")
                        .HasDatabaseName("price_item");

                    b.ToTable("price", (string)null);
                });

            modelBuilder.Entity("Armory.Store.RecipeReagentRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recipe_id");

                    b.Property<long>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("Tiers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tiers");

                    b.HasKey("RealmSlug", "Name", "RecipeId", "Slot");

                    b.ToTable("recipe_reagent", (string)null);
                });

            modelBuilder.Entity("Armory.Store.RecipeRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recipe_id");

                    b.Property<long>("Makes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("makes");

                    b.Property<long>("OutputId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_id");

                    b.Property<string>("Recipe")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recipe");

                    b.HasKey("RealmSlug", "Name", "RecipeId");

                    b.ToTable("recipe", (string)null);
                });

            modelBuilder.Entity("Armory.Store.ResponseRow", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("body");

                    b.Property<string>("FetchedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<string>("LastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified");

                    b.HasKey("Url");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("response_fetched_at");

                    b.ToTable("response", (string)null);
                });

            modelBuilder.Entity("Armory.Store.RunRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Baseline")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("baseline");

                    b.Property<string>("Cohort")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cohort");

                    b.Property<long>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("is_current");

                    b.Property<string>("Key")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("run_key");

                    b.ToTable("run", (string)null);
                });

            modelBuilder.Entity("Armory.Store.SessionRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("EndedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("json");

                    b.HasKey("RealmSlug", "Name", "StartedAt");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("session_started_at");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Armory.Store.SnapshotRow", b =>
                {
                    b.Property<long>("Realm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realm");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("Variant")
                        .HasColumnType("TEXT")
                        .HasColumnName("variant");

                    b.Property<long>("Cheapest")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cheapest");

                    b.Property<long>("Listings")
                        .HasColumnType("INTEGER")
                        .HasColumnName("listings");

                    b.Property<long>("Median")
                        .HasColumnType("INTEGER")
                        .HasColumnName("median");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("SeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("seen_at");

                    b.Property<long>("Tenth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenth");

                    b.HasKey("Realm", "ItemId", "Variant");

                    b.ToTable("snapshot", (string)null);
                });

            modelBuilder.Entity("Armory.Store.SyncStateRow", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Name");

                    b.ToTable("sync_state", (string)null);
                });

            modelBuilder.Entity("Armory.Store.TallyRow", b =>
                {
                    b.Property<string>("RealmSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_slug");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<long>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.HasKey("RealmSlug", "Name", "Kind", "Key");

                    b.ToTable("tally", (string)null);
                });

            modelBuilder.Entity("Armory.Store.WarbandItemRow", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<long>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count");

                    b.HasKey("ItemId");

                    b.ToTable("warband_item", (string)null);
                });

            modelBuilder.Entity("Armory.Store.WatchedRealmRow", b =>
                {
                    b.Property<long>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realm_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.HasKey("RealmId");

                    b.ToTable("watched_realm", (string)null);
                });

            modelBuilder.Entity("Armory.Store.WatchedRow", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.HasKey("ItemId");

                    b.ToTable("watched", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
