//! Getting a token out of Battle.net.
//!
//! Battle.net does not support PKCE. Blizzard developer relations confirmed in
//! October 2024 that every registered client is a *confidential* client and
//! there is no public/native mode: "Because PKCE is not a replacement for client
//! authentication, it does not allow treating a public client as a confidential
//! client." A client secret is therefore mandatory, and shipping one inside a
//! distributed binary is both a terms violation and a way to pool every user of
//! the application into one 36,000-per-hour quota.
//!
//! So Armory has no secret of its own. The user registers their own API client
//! and Armory holds the credentials on their behalf. That is what every
//! self-hosted tool in this space does, it is what Blizzard's own quick-start
//! tells a developer to do, and it hands each user their own quota.
//!
//! The redirect is a loopback listener. Blizzard accepts `http://127.0.0.1:PORT`
//! — its own sample client uses `http://localhost:8080` — and rejects custom URI
//! schemes outright, so a real HTTP server on a fixed port is not a shortcut,
//! it is the only supported shape. The port is fixed because the redirect URI
//! must match the registered string exactly; there is no RFC 8252 loopback
//! wildcard here.

use serde::{Deserialize, Serialize};

use super::super::{parse_json, Outcome, Reason, Request, SourceId};

/// Where the sign-in page lives.
const AUTHORIZE: &str = "https://oauth.battle.net/authorize";
/// Where a code is exchanged for a token.
const TOKEN: &str = "https://oauth.battle.net/token";

/// The port the loopback listener binds, and the one the user registers.
///
/// Fixed rather than ephemeral: the redirect URI has to match what was
/// registered, character for character. 21451 is in the ephemeral range but
/// unassigned, which keeps the collision odds low without needing a permanent
/// allocation.
pub const REDIRECT_PORT: u16 = 21451;

/// The redirect URI to register, and to send.
pub fn redirect_uri() -> String {
    format!("http://127.0.0.1:{REDIRECT_PORT}/callback")
}

/// The scope that buys access to a character's profile.
const SCOPE: &str = "wow.profile";

/// A registered API client: what the user creates and pastes in.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClientCredentials {
    pub id: String,
    pub secret: String,
}

impl ClientCredentials {
    /// HTTP Basic, which is how the token endpoint wants the client identified —
    /// on both the authorization-code exchange and the refresh, even though the
    /// exchange also carries a code that is itself a secret.
    fn basic(&self) -> String {
        format!("Basic {}", base64(format!("{}:{}", self.id, self.secret)))
    }
}

/// A token, and when it stops working.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Token {
    pub access: String,
    /// Seconds from issue. Blizzard documents 24 hours and mostly honours it.
    pub expires_in: i64,
    /// Battle.net's own staff have said refresh tokens are not issued, yet the
    /// discovery document lists the grant and some responses carry the field.
    /// It is kept when present and never relied upon: [`refresh`] exists, and
    /// the sign-in flow is the fallback when it does not work.
    pub refresh: Option<String>,
}

/// The URL to open in a browser to begin signing in.
///
/// `state` is generated by the caller and checked when the redirect lands. It is
/// the only defence here against a redirect that did not come from the flow we
/// started, since there is no PKCE verifier to fall back on.
pub fn authorize_url(client: &ClientCredentials, state: &str) -> String {
    format!(
        "{AUTHORIZE}?client_id={}&scope={}&state={}&redirect_uri={}&response_type=code",
        super::encode(&client.id),
        super::encode(SCOPE),
        super::encode(state),
        super::encode(&redirect_uri()),
    )
}

/// Exchange the code the redirect delivered for a token.
pub fn exchange(client: &ClientCredentials, code: &str) -> Request {
    let body = format!(
        "grant_type=authorization_code&code={}&redirect_uri={}",
        super::encode(code),
        super::encode(&redirect_uri()),
    );
    Request::post(SourceId::BattleNetOAuth, TOKEN, body).header("Authorization", client.basic())
}

/// Trade a refresh token for a fresh access token.
///
/// Whether this works is genuinely uncertain — see [`Token::refresh`]. It is
/// attempted first because when it does work it saves the user a browser round
/// trip, and its failure is not an error, it is a prompt to sign in again.
pub fn refresh(client: &ClientCredentials, refresh_token: &str) -> Request {
    let body = format!(
        "grant_type=refresh_token&refresh_token={}",
        super::encode(refresh_token)
    );
    Request::post(SourceId::BattleNetOAuth, TOKEN, body).header("Authorization", client.basic())
}

/// Read a token out of the token endpoint's answer.
pub fn parse_token(body: &[u8]) -> Outcome<Token> {
    let value = match parse_json(SourceId::BattleNetOAuth, body) {
        Ok(value) => value,
        Err(outcome) => return outcome,
    };

    // The endpoint reports a bad secret as a 400 with a JSON error body rather
    // than a status the transport layer would catch, so it is read here.
    if let Some(error) = value.get("error").and_then(|error| error.as_str()) {
        let detail = value
            .get("error_description")
            .and_then(|text| text.as_str())
            .unwrap_or(error);
        return Outcome::Unusable(Reason::Unauthorised(detail.to_string()));
    }

    let Some(access) = value.get("access_token").and_then(|token| token.as_str()) else {
        return Outcome::Stale(Reason::Malformed(
            "the token response carried no access_token".into(),
        ));
    };

    Outcome::Found(Token {
        access: access.to_string(),
        expires_in: value
            .get("expires_in")
            .and_then(|seconds| seconds.as_i64())
            // A response with no lifetime is treated as an hour rather than as
            // forever. Being wrong in this direction costs one extra sign-in.
            .unwrap_or(3600),
        refresh: value
            .get("refresh_token")
            .and_then(|token| token.as_str())
            .map(str::to_string),
    })
}

/// Pull the `code` and `state` out of the query string the redirect carried.
///
/// The user may also have refused, in which case there is an `error` and no
/// code; that is a decision, not a fault, and it reads as one.
pub fn parse_callback(query: &str) -> Result<(String, String), Reason> {
    let mut code = None;
    let mut state = None;
    let mut error = None;

    for pair in query.trim_start_matches('?').split('&') {
        let Some((name, value)) = pair.split_once('=') else {
            continue;
        };
        let value = decode(value);
        match name {
            "code" => code = Some(value),
            "state" => state = Some(value),
            "error_description" => error = Some(value),
            "error" if error.is_none() => error = Some(value),
            _ => {}
        }
    }

    if let Some(error) = error {
        return Err(Reason::Unauthorised(error));
    }
    match (code, state) {
        (Some(code), Some(state)) => Ok((code, state)),
        _ => Err(Reason::Malformed(
            "the sign-in redirect carried no code".into(),
        )),
    }
}

/// Percent-decode one query parameter value.
fn decode(value: &str) -> String {
    let bytes = value.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        match bytes[index] {
            b'%' if index + 2 < bytes.len() => {
                let hex = std::str::from_utf8(&bytes[index + 1..index + 3]).unwrap_or("");
                match u8::from_str_radix(hex, 16) {
                    Ok(byte) => {
                        out.push(byte);
                        index += 3;
                    }
                    Err(_) => {
                        out.push(bytes[index]);
                        index += 1;
                    }
                }
            }
            b'+' => {
                out.push(b' ');
                index += 1;
            }
            byte => {
                out.push(byte);
                index += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// Base64, for the one Basic header this module sends.
///
/// Sixteen lines against a dependency that would be compiled into every build
/// to encode one string per sign-in. The alphabet is fixed and the padding
/// rules have not moved since 1987.
fn base64(input: String) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let bytes = input.as_bytes();
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);

    for chunk in bytes.chunks(3) {
        let packed = chunk
            .iter()
            .enumerate()
            .fold(0u32, |packed, (index, byte)| {
                packed | (*byte as u32) << (16 - index * 8)
            });
        for index in 0..4 {
            if index <= chunk.len() {
                out.push(ALPHABET[(packed >> (18 - index * 6) & 0x3F) as usize] as char);
            } else {
                out.push('=');
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn client() -> ClientCredentials {
        ClientCredentials {
            id: "abc123".into(),
            secret: "shhh".into(),
        }
    }

    #[test]
    fn the_redirect_is_loopback_on_a_fixed_port() {
        // Blizzard rejects custom URI schemes and matches the registered string
        // exactly, so neither the scheme nor the port may drift.
        let uri = redirect_uri();
        assert!(uri.starts_with("http://127.0.0.1:"), "{uri}");
        assert!(uri.ends_with("/callback"), "{uri}");
        assert!(!uri.starts_with("armory://"));
    }

    #[test]
    fn the_authorize_url_carries_the_encoded_redirect_and_the_state() {
        let url = authorize_url(&client(), "nonce-42");
        assert!(url.starts_with(AUTHORIZE));
        assert!(url.contains("client_id=abc123"));
        assert!(url.contains("scope=wow.profile"));
        assert!(url.contains("state=nonce-42"));
        assert!(url.contains("response_type=code"));
        // The redirect must arrive encoded or Battle.net reads it as extra
        // parameters and refuses the whole request.
        assert!(url.contains("redirect_uri=http%3A%2F%2F127.0.0.1%3A"));
    }

    #[test]
    fn the_secret_never_reaches_the_url() {
        // It goes in a Basic header on the token call and nowhere else. A secret
        // in a query string ends up in logs and in browser history.
        let url = authorize_url(&client(), "nonce");
        assert!(!url.contains("shhh"), "{url}");

        let request = exchange(&client(), "the-code");
        assert!(!request.url.contains("shhh"));
        assert!(!request.body.as_deref().unwrap_or("").contains("shhh"));
        assert!(request
            .headers
            .iter()
            .any(|(name, value)| name == "Authorization" && value.starts_with("Basic ")));
    }

    #[test]
    fn basic_auth_encodes_the_pair_the_way_the_endpoint_expects() {
        // Checked against a known vector rather than against our own encoder.
        assert_eq!(base64("abc123:shhh".to_string()), "YWJjMTIzOnNoaGg=");
        assert_eq!(base64("a".to_string()), "YQ==");
        assert_eq!(base64("ab".to_string()), "YWI=");
        assert_eq!(base64("abc".to_string()), "YWJj");
    }

    #[test]
    fn a_token_response_is_read_whole() {
        let body = br#"{"access_token":"tok","token_type":"bearer","expires_in":86399}"#;
        let token = parse_token(body).found().expect("a token");
        assert_eq!(token.access, "tok");
        assert_eq!(token.expires_in, 86399);
        assert_eq!(token.refresh, None);
    }

    #[test]
    fn a_refresh_token_is_kept_when_offered() {
        // Staff say these are not issued; the discovery document says otherwise.
        // Keep it when it appears and never depend on it.
        let body = br#"{"access_token":"tok","expires_in":100,"refresh_token":"r"}"#;
        let token = parse_token(body).found().expect("a token");
        assert_eq!(token.refresh.as_deref(), Some("r"));
    }

    #[test]
    fn a_missing_lifetime_expires_soon_rather_than_never() {
        let token = parse_token(br#"{"access_token":"tok"}"#)
            .found()
            .expect("a token");
        assert_eq!(token.expires_in, 3600);
    }

    #[test]
    fn a_bad_secret_reads_as_a_sign_in_problem_not_a_broken_parser() {
        // The endpoint answers 400 with a JSON error body. Reporting that as
        // Stale would send someone looking for a bug in the parser.
        let body = br#"{"error":"invalid_client","error_description":"bad secret"}"#;
        match parse_token(body) {
            Outcome::Unusable(Reason::Unauthorised(detail)) => assert_eq!(detail, "bad secret"),
            other => panic!("{other:?}"),
        }
    }

    #[test]
    fn a_body_that_is_not_json_is_stale() {
        assert!(matches!(
            parse_token(b"<html>maintenance</html>"),
            Outcome::Stale(_)
        ));
    }

    #[test]
    fn the_callback_yields_the_code_and_the_state() {
        let (code, state) = parse_callback("?code=abc&state=nonce-42").expect("a code");
        assert_eq!(code, "abc");
        assert_eq!(state, "nonce-42");
    }

    #[test]
    fn a_refusal_at_the_sign_in_page_is_a_decision_not_a_fault() {
        // Someone clicking Cancel must not produce "unreadable response".
        let error = parse_callback("?error=access_denied&error_description=the%20user%20said%20no")
            .expect_err("a refusal");
        assert!(matches!(error, Reason::Unauthorised(_)), "{error:?}");
        assert!(error.to_string().contains("the user said no"));
    }

    #[test]
    fn a_redirect_with_no_code_is_malformed() {
        assert!(matches!(
            parse_callback("?state=nonce").expect_err("no code"),
            Reason::Malformed(_)
        ));
    }
}
